### ISSUE TITLE
Add Dockerfile and deployment config

### ISSUE THREAD

**Issue by butzist** [tamediadigital/go-processing-boilerplate#4]

**Comment by ciric92** [comment]
why?

**Comment by butzist** [comment]
Isn't that also boilerplate code? Right now I wouldn't know where to find that code ;)

**Comment by butzist** [comment]
Also if the tech behind packaging / building changes, I would like to merge the updated config

**Comment by PetarLotrean** [comment]
This is a library, a common project that we use in other projects, such as [this one](https://github.com/tamediadigital/mercator-to-clickhouse).

This is a project that is not deployed, so no need for dockerfile and deploy config.

**Comment by butzist** [comment]
Fair enough, consider this ticked closed. We need a template repo then instead.
